### ISSUE TITLE
Instances names are green, although raid id is active

### ISSUE THREAD

**Issue by Scanda85** [obstrom/TitanRaidLockout#11]
Hi, 
i have a bug with the actual version 1.0.1
I have an active ID for BWL and MC.
At the Titan Panel are all instances shown. But all are green. 
MC and BWL should be in red color.

When i mouseover the correct IDs and reset timers are shown.

**Comment by obstrom** [comment]
Hi, thanks for the bug report!

It sounds as if the panel is not updating as it should in your game. Could you test the following and get back to me? It would help me locate what is happening since I am not experiencing this issue in my client.

1. Are all instances always shown as green? Or do they change to the correct color of red after some time? Maybe after a loading screen?
2. When you first login to a character, are all the instances green? If you type `/rl` (this reloads the UI) do the correct instance names then turn red?

**Comment by Scanda85** [comment]
1. Actual only ZG is shown red. They don't change after relaoding the screen
2. Also when i login the colors are green (ZG = red)

But it could be following problems:
- Don't update correctly
- If there is an update: ID + all bosses clear = green, ID and still open bosses = red

![image](https://user-images.githubusercontent.com/20796795/91656819-28f33480-eabc-11ea-9234-da403ac6989a.png)

**Comment by obstrom** [comment]
Oh, I see the issue now! It's probably because your game client is not in English (it's in German correct?). I did not account for the possible issues with locale differences when coding this.

To show the names as red in the panel it checks the names of every instance you are locked into against a table of known instance names (in English) to know which should be red, the rest become green. The reason only Zul'Gurub is showing correctly for you is because it's the only instance that has the same name in English.

There should be no problem fixing this. I'll either add support for all the locales, or even better, see if I can make the offending code not rely on the instance names.

I'll try and have an update out to fix this asap.

**Comment by Scanda85** [comment]
correct my client is in german.
sounds great that you found the problem

**Comment by obstrom** [comment]
I have an update ready. @Scanda85 would you be willing to help me test that this update is working for you, before I publish this as an official update?

1. Download the [development version of the addon](https://github.com/obstrom/TitanRaidLockout/archive/develop.zip)
2. Go to your Addons folder ( `...\World of Warcraft\_classic_\Interface\AddOns` )
3. Delete the `TitanRaidLockout` folder
4. Extract the `TitanRaidLockout-develop.zip` in the Addons folder. And rename the folder from `TitanRaidLockout-develop` to just `TitanRaidLockout` (i.e remove the "-develop" from the folder name)
5. Launch the game and see if the issue is fixed

If this works it should in theory also fix the problem for Spanish, French and Russian clients.

Thanks for the assistance in resolving this! 😃

**Comment by Scanda85** [comment]
Thanks, current I'm not at home. I will test this during the day.

Am 30. August 2020 13:32:42 schrieb Oscar Bergström <notifications@github.com>:

**Comment by Scanda85** [comment]
Getting some error messages, after login into the game with my char or /reload:

`Date: 2020-08-30 19:59:06
ID: 3
Error occured in: Global
Count: 1
Message: ...AddOns\TitanRaidLockout\TitanRaidLockout_locales.lua line 3:
   attempt to index global 'L' (a string value)
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   [C]: ?
   ...AddOns\TitanRaidLockout\TitanRaidLockout_locales.lua:3: in main chunk
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693`


`Date: 2020-08-30 19:59:06
ID: 2
Error occured in: Global
Count: 1
Message: [string "TitanPanelTitanRaidLockoutButton:OnLoad"] line 1:
   attempt to call global 'TRaidLockout_OnLoad' (a nil value)
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   [C]: TRaidLockout_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693`

`Date: 2020-08-30 19:59:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\TitanRaidLockout\TitanRaidLockout.lua line 13:
   '}' expected (to close '{' at line 11) near '['
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   [C]: ?
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693`

**Comment by obstrom** [comment]
Thanks for the detailed error logs @Scanda85. This should be resolved now. I managed to change my client language to German and test out that it's actually working.

You could try downloading the [development version](https://github.com/obstrom/TitanRaidLockout/archive/develop.zip) again and test yourself. The latest development version is `1.0.21-dev`

**Comment by Scanda85** [comment]
With the new development version the colours of the ids work fine. 

![image](https://user-images.githubusercontent.com/20796795/91682682-a79ab100-eb52-11ea-8b7e-cdc6802dafbf.png)

But there are still two error messages:

`Date: 2020-08-31 06:23:44
ID: 1
Error occured in: Global
Count: 1
Message: AceLocale-3.0: TitanClassic: Missing entry for 'Raid Lockout'
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   ...Inventory\Externals\Ace3\AceLocale\AceLocale-3.0.lua:31:
      ...Inventory\Externals\Ace3\AceLocale\AceLocale-3.0.lua:29
   ...terface\AddOns\TitanRaidLockout\TitanRaidLockout.lua:37: TRaidLockout_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
None`

`Date: 2020-08-31 06:23:44
ID: 2
Error occured in: Global
Count: 1
Message: AceLocale-3.0: TitanClassic: Missing entry for 'Information'
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   ...Inventory\Externals\Ace3\AceLocale\AceLocale-3.0.lua:31:
      ...Inventory\Externals\Ace3\AceLocale\AceLocale-3.0.lua:29
   ...terface\AddOns\TitanRaidLockout\TitanRaidLockout.lua:42: TRaidLockout_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
None`

**Comment by obstrom** [comment]
Excellent, that is working as intended then.
I kept developing other parts on this build/branch, so those errors are not related to this main issue- I'll have those errors fixed in a moment. Thanks for bringing them up however!

I also implemented correct localization support. So, if there is any part of the addon you wish me to translate it can now be easily done. You can look at the [_locales.lua file](https://github.com/obstrom/TitanRaidLockout/blob/develop/TitanRaidLockout_locales.lua) for a list of what can be translated.

I will make a new official update available during the day today, including fixes to this issue. Curse/Twitch might take a moment however to approve the update release.

Thanks again for the assistance. I hope you enjoy the addon! 😃

**Comment by Scanda85** [comment]
Ok, great. 
I will close this issue
And i will write a new feature request.
