### ISSUE TITLE
WoTLK?

### ISSUE THREAD

**Issue by 1Botnet** [obstrom/TitanRaidLockout#27]
Will this be getting a WoTLK update?

**Comment by obstrom** [comment]
Hi, I'm not personally playing any more I had not given it much thought until your question.

I could attempt to "blindly" add WoTLK support to the TBC version. So the addon should function the same, but also show WoTLK raids and instances. Hopefully the WoTLK client handles this stuff similarly to how the TBC client did, then it should be quite straightforward.

I'll have a look at it and see if I can have a beta version out soon. Time-wise it depends on how straightforward it ends up being. I'll post any updates in this issue thread.

I would really appreciate any help possible with testing from the community, since I have no way to play test and find bugs myself. Also if any other developer wants to contribute to the project, I would welcome the assistance.

**Comment by 1Botnet** [comment]
I'll gladly test it out.

Currently there are no LUA errors. It simply isn't recognizing the dungeon lock outs.

Raid kicks off next week.

**Comment by obstrom** [comment]
Great, thanks for the assistance @1Botnet! 🙌🏻 

I got an alpha version of the update ready now on Github ([download for manual install](https://github.com/obstrom/TitanRaidLockout/archive/refs/heads/dev-1.3.0-wotlk.zip)) and should soon be available on [Curse](https://www.curseforge.com/wow/addons/titan-panel-classic-raid-lockout/files) as well.

Will await feedback before I either make fixes or push to release.

## Changes
1. Added support for all WoTLK raids and heroics in one go. For abbreviations (since I'm not actively playing and not sure what ppl are using right now) I looked up on [https://wowwiki-archive.fandom.com/](https://wowwiki-archive.fandom.com/) what they listed as abbreviations. Full list of these can be found [here](https://github.com/obstrom/TitanRaidLockout/blob/dev-1.3.0-wotlk/TitanRaidLockout_locales.lua).
2. Added a new toggle setting to hide/show TBC instances, since these are now stale but some ppl might still be running them (farms possibly?) and want to track them still.

Hopefully both of these work well on first try 🤞🏻 🙈

**Comment by 1Botnet** [comment]
Getting 2 LUA errors. Addon won't load.

```
2x [string "TitanPanelTitanRaidLockoutButton:OnLoad"]:1: attempt to call global 'TRaidLockout_OnLoad' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
self = TitanPanelTitanRaidLockoutButton {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = TitanPanelTitanRaidLockoutButton {
 0 = <userdata>
}
(*temporary) = "attempt to call global 'TRaidLockout_OnLoad' (a nil value)"
```
------------------------------
```
2x TitanRaidLockout\TitanRaidLockout-v1.3.0-snapshot-classic-wotlk.lua:100: attempt to index global 'LOCALIZED_ALL_RAID_NAMES' (a nil value)
[string "@TitanRaidLockout\TitanRaidLockout-v1.3.0-snapshot-classic-wotlk.lua"]:100: in main chunk

Locals:
addonName = "TitanRaidLockout"
addonTable = <table> {
}
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 788
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 406
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 DetailsWindowOptionsBarTextEditorEntryNumberLines = DetailsWindowOptionsBarTextEditorEntryNumberLines {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 LoseControlOptionsPanelpetFriendlyDisarmDebuffText = LoseControlOptionsPanelpetFriendlyDisarmDebuffText {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:603
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 CONSOLIDATED_BUFFS_PER_ROW = 4
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML\AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 SLASH_LibQTip1 = "/qtip"
 LFGBulletinBoardO_Edit_317CboxOnDebug = LFGBulletinBoardO_Edit_317CboxOnDebug {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 VOICEMACRO_4_Sc_1_FEMALE = "Help me attack!"
 JoinSkirmish = <function> defined =[C]:-1
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 PetPaperDollFrameTab3Right = PetPaperDollFrameTab3Right {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML\ChatFrame.lua:1128
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 SpyStatsPlayerHistoryFrameListFrameLine10Level = SpyStatsPlayerHistoryFrameListFrameLine10Level {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameMana
```

**Comment by obstrom** [comment]
@1Botnet thanks for the feedback! I wrapped the errors in your comment with ` ``` ` so it's easier to read.

I think I've fixed this issue now. New version on curse soon, manual download [here](https://github.com/obstrom/TitanRaidLockout/archive/refs/heads/dev-1.3.0-wotlk.zip). Could you please try again with that version (called Alpha-2)?

**Comment by 1Botnet** [comment]
No LUA errors now. 

I was able to do one heroic but it didn't pull over to Titan Panel until I opened Raid Info.

I'll try to knock out another one and see if that is still an issue.


Edit: Must of been a delay. Everything seems to pull over just fine. Might just need to zone /reload for it to recognize the new locked instance ID. Thanks for the update.

**Comment by obstrom** [comment]
Awesome! Thanks again for the help @1Botnet. 🙌🏻

> Edit: Must of been a delay. Everything seems to pull over just fine.

Is it always delayed, or is this only happening sometimes? The addon listens for an event in the game client called `UPDATE_INSTANCE_INFO`. The delay might happen if Blizz changed this event to not fire the moment you get locked (it did in Classic and for the most part Classic-TBC).

Regardless it sounds like it’s working fine enough to release. I’ll make a normal release version available later tonight on Curse and Github, and hotfix from there.

Cheers!

**Comment by obstrom** [comment]
Seems to be working fine in release. Closing issue.
